apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-backend
  template:
    metadata:
      labels:
        app: blog-backend
    spec:
      containers:
        - name: blog-backend-container
          image: indupriyavempati/blogapp:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "db_url/"
            - name: DB_NAME
              value: "blog-db"
            - name: COLLECTION_NAME
              value: "posts"
